// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AuthPayload struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

type Mutation struct {
}

type Query struct {
}

type UserProfile struct {
	UserID               string     `json:"user_id"`
	Name                 *string    `json:"name,omitempty"`
	Phone                *string    `json:"phone,omitempty"`
	PhotoID              *string    `json:"photo_id,omitempty"`
	NotificationsEnabled bool       `json:"notifications_enabled"`
	Subscriptions        []string   `json:"subscriptions"`
	UpdatedAt            *time.Time `json:"updated_at,omitempty"`
}
