// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: adminservice/presentation/grpc/proto/adminservice.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssignRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleRequest) Reset() {
	*x = AssignRoleRequest{}
	mi := &file_adminservice_presentation_grpc_proto_adminservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleRequest) ProtoMessage() {}

func (x *AssignRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adminservice_presentation_grpc_proto_adminservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleRequest.ProtoReflect.Descriptor instead.
func (*AssignRoleRequest) Descriptor() ([]byte, []int) {
	return file_adminservice_presentation_grpc_proto_adminservice_proto_rawDescGZIP(), []int{0}
}

func (x *AssignRoleRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AssignRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Assigned      bool                   `protobuf:"varint,2,opt,name=assigned,proto3" json:"assigned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleResponse) Reset() {
	*x = AssignRoleResponse{}
	mi := &file_adminservice_presentation_grpc_proto_adminservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleResponse) ProtoMessage() {}

func (x *AssignRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adminservice_presentation_grpc_proto_adminservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleResponse.ProtoReflect.Descriptor instead.
func (*AssignRoleResponse) Descriptor() ([]byte, []int) {
	return file_adminservice_presentation_grpc_proto_adminservice_proto_rawDescGZIP(), []int{1}
}

func (x *AssignRoleResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AssignRoleResponse) GetAssigned() bool {
	if x != nil {
		return x.Assigned
	}
	return false
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_adminservice_presentation_grpc_proto_adminservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adminservice_presentation_grpc_proto_adminservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_adminservice_presentation_grpc_proto_adminservice_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_adminservice_presentation_grpc_proto_adminservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adminservice_presentation_grpc_proto_adminservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_adminservice_presentation_grpc_proto_adminservice_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetUserResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type Profile struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UserId               uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	PhotoId              string                 `protobuf:"bytes,4,opt,name=photo_id,json=photoId,proto3" json:"photo_id,omitempty"`
	NotificationsEnabled bool                   `protobuf:"varint,5,opt,name=notifications_enabled,json=notificationsEnabled,proto3" json:"notifications_enabled,omitempty"`
	Subscriptions        []string               `protobuf:"bytes,6,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_adminservice_presentation_grpc_proto_adminservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_adminservice_presentation_grpc_proto_adminservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_adminservice_presentation_grpc_proto_adminservice_proto_rawDescGZIP(), []int{4}
}

func (x *Profile) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Profile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Profile) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Profile) GetPhotoId() string {
	if x != nil {
		return x.PhotoId
	}
	return ""
}

func (x *Profile) GetNotificationsEnabled() bool {
	if x != nil {
		return x.NotificationsEnabled
	}
	return false
}

func (x *Profile) GetSubscriptions() []string {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *Profile) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_adminservice_presentation_grpc_proto_adminservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adminservice_presentation_grpc_proto_adminservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_adminservice_presentation_grpc_proto_adminservice_proto_rawDescGZIP(), []int{5}
}

func (x *GetProfileRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetProfilesListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint32                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfilesListRequest) Reset() {
	*x = GetProfilesListRequest{}
	mi := &file_adminservice_presentation_grpc_proto_adminservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfilesListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfilesListRequest) ProtoMessage() {}

func (x *GetProfilesListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adminservice_presentation_grpc_proto_adminservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfilesListRequest.ProtoReflect.Descriptor instead.
func (*GetProfilesListRequest) Descriptor() ([]byte, []int) {
	return file_adminservice_presentation_grpc_proto_adminservice_proto_rawDescGZIP(), []int{6}
}

func (x *GetProfilesListRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetProfilesListRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetProfilesListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*Profile             `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfilesListResponse) Reset() {
	*x = GetProfilesListResponse{}
	mi := &file_adminservice_presentation_grpc_proto_adminservice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfilesListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfilesListResponse) ProtoMessage() {}

func (x *GetProfilesListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adminservice_presentation_grpc_proto_adminservice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfilesListResponse.ProtoReflect.Descriptor instead.
func (*GetProfilesListResponse) Descriptor() ([]byte, []int) {
	return file_adminservice_presentation_grpc_proto_adminservice_proto_rawDescGZIP(), []int{7}
}

func (x *GetProfilesListResponse) GetProfiles() []*Profile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type BanUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanUserRequest) Reset() {
	*x = BanUserRequest{}
	mi := &file_adminservice_presentation_grpc_proto_adminservice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanUserRequest) ProtoMessage() {}

func (x *BanUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adminservice_presentation_grpc_proto_adminservice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanUserRequest.ProtoReflect.Descriptor instead.
func (*BanUserRequest) Descriptor() ([]byte, []int) {
	return file_adminservice_presentation_grpc_proto_adminservice_proto_rawDescGZIP(), []int{8}
}

func (x *BanUserRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type BanUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Banned        bool                   `protobuf:"varint,1,opt,name=banned,proto3" json:"banned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanUserResponse) Reset() {
	*x = BanUserResponse{}
	mi := &file_adminservice_presentation_grpc_proto_adminservice_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanUserResponse) ProtoMessage() {}

func (x *BanUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adminservice_presentation_grpc_proto_adminservice_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanUserResponse.ProtoReflect.Descriptor instead.
func (*BanUserResponse) Descriptor() ([]byte, []int) {
	return file_adminservice_presentation_grpc_proto_adminservice_proto_rawDescGZIP(), []int{9}
}

func (x *BanUserResponse) GetBanned() bool {
	if x != nil {
		return x.Banned
	}
	return false
}

type UnbanUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbanUserRequest) Reset() {
	*x = UnbanUserRequest{}
	mi := &file_adminservice_presentation_grpc_proto_adminservice_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbanUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbanUserRequest) ProtoMessage() {}

func (x *UnbanUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adminservice_presentation_grpc_proto_adminservice_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbanUserRequest.ProtoReflect.Descriptor instead.
func (*UnbanUserRequest) Descriptor() ([]byte, []int) {
	return file_adminservice_presentation_grpc_proto_adminservice_proto_rawDescGZIP(), []int{10}
}

func (x *UnbanUserRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UnbanUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unbanned      bool                   `protobuf:"varint,1,opt,name=unbanned,proto3" json:"unbanned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbanUserResponse) Reset() {
	*x = UnbanUserResponse{}
	mi := &file_adminservice_presentation_grpc_proto_adminservice_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbanUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbanUserResponse) ProtoMessage() {}

func (x *UnbanUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adminservice_presentation_grpc_proto_adminservice_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbanUserResponse.ProtoReflect.Descriptor instead.
func (*UnbanUserResponse) Descriptor() ([]byte, []int) {
	return file_adminservice_presentation_grpc_proto_adminservice_proto_rawDescGZIP(), []int{11}
}

func (x *UnbanUserResponse) GetUnbanned() bool {
	if x != nil {
		return x.Unbanned
	}
	return false
}

var File_adminservice_presentation_grpc_proto_adminservice_proto protoreflect.FileDescriptor

const file_adminservice_presentation_grpc_proto_adminservice_proto_rawDesc = "" +
	"\n" +
	"7adminservice/presentation/grpc/proto/adminservice.proto\x12\x0fadminservice.v1\x1a\x1fgoogle/protobuf/timestamp.proto\",\n" +
	"\x11AssignRoleRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"I\n" +
	"\x12AssignRoleResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1a\n" +
	"\bassigned\x18\x02 \x01(\bR\bassigned\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"T\n" +
	"\x0fGetUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"\xfd\x01\n" +
	"\aProfile\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x19\n" +
	"\bphoto_id\x18\x04 \x01(\tR\aphotoId\x123\n" +
	"\x15notifications_enabled\x18\x05 \x01(\bR\x14notificationsEnabled\x12$\n" +
	"\rsubscriptions\x18\x06 \x03(\tR\rsubscriptions\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\",\n" +
	"\x11GetProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"F\n" +
	"\x16GetProfilesListRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\rR\x06offset\"O\n" +
	"\x17GetProfilesListResponse\x124\n" +
	"\bprofiles\x18\x01 \x03(\v2\x18.adminservice.v1.ProfileR\bprofiles\")\n" +
	"\x0eBanUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\")\n" +
	"\x0fBanUserResponse\x12\x16\n" +
	"\x06banned\x18\x01 \x01(\bR\x06banned\"+\n" +
	"\x10UnbanUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"/\n" +
	"\x11UnbanUserResponse\x12\x1a\n" +
	"\bunbanned\x18\x01 \x01(\bR\bunbanned2\x87\x04\n" +
	"\fAdminService\x12L\n" +
	"\aBanUser\x12\x1f.adminservice.v1.BanUserRequest\x1a .adminservice.v1.BanUserResponse\x12R\n" +
	"\tUnbanUser\x12!.adminservice.v1.UnbanUserRequest\x1a\".adminservice.v1.UnbanUserResponse\x12U\n" +
	"\n" +
	"AssignRole\x12\".adminservice.v1.AssignRoleRequest\x1a#.adminservice.v1.AssignRoleResponse\x12L\n" +
	"\aGetUser\x12\x1f.adminservice.v1.GetUserRequest\x1a .adminservice.v1.GetUserResponse\x12J\n" +
	"\n" +
	"GetProfile\x12\".adminservice.v1.GetProfileRequest\x1a\x18.adminservice.v1.Profile\x12d\n" +
	"\x0fGetProfilesList\x12'.adminservice.v1.GetProfilesListRequest\x1a(.adminservice.v1.GetProfilesListResponseB&Z$adminservice/presentation/grpc/pb;pbb\x06proto3"

var (
	file_adminservice_presentation_grpc_proto_adminservice_proto_rawDescOnce sync.Once
	file_adminservice_presentation_grpc_proto_adminservice_proto_rawDescData []byte
)

func file_adminservice_presentation_grpc_proto_adminservice_proto_rawDescGZIP() []byte {
	file_adminservice_presentation_grpc_proto_adminservice_proto_rawDescOnce.Do(func() {
		file_adminservice_presentation_grpc_proto_adminservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_adminservice_presentation_grpc_proto_adminservice_proto_rawDesc), len(file_adminservice_presentation_grpc_proto_adminservice_proto_rawDesc)))
	})
	return file_adminservice_presentation_grpc_proto_adminservice_proto_rawDescData
}

var file_adminservice_presentation_grpc_proto_adminservice_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_adminservice_presentation_grpc_proto_adminservice_proto_goTypes = []any{
	(*AssignRoleRequest)(nil),       // 0: adminservice.v1.AssignRoleRequest
	(*AssignRoleResponse)(nil),      // 1: adminservice.v1.AssignRoleResponse
	(*GetUserRequest)(nil),          // 2: adminservice.v1.GetUserRequest
	(*GetUserResponse)(nil),         // 3: adminservice.v1.GetUserResponse
	(*Profile)(nil),                 // 4: adminservice.v1.Profile
	(*GetProfileRequest)(nil),       // 5: adminservice.v1.GetProfileRequest
	(*GetProfilesListRequest)(nil),  // 6: adminservice.v1.GetProfilesListRequest
	(*GetProfilesListResponse)(nil), // 7: adminservice.v1.GetProfilesListResponse
	(*BanUserRequest)(nil),          // 8: adminservice.v1.BanUserRequest
	(*BanUserResponse)(nil),         // 9: adminservice.v1.BanUserResponse
	(*UnbanUserRequest)(nil),        // 10: adminservice.v1.UnbanUserRequest
	(*UnbanUserResponse)(nil),       // 11: adminservice.v1.UnbanUserResponse
	(*timestamppb.Timestamp)(nil),   // 12: google.protobuf.Timestamp
}
var file_adminservice_presentation_grpc_proto_adminservice_proto_depIdxs = []int32{
	12, // 0: adminservice.v1.Profile.updated_at:type_name -> google.protobuf.Timestamp
	4,  // 1: adminservice.v1.GetProfilesListResponse.profiles:type_name -> adminservice.v1.Profile
	8,  // 2: adminservice.v1.AdminClient.BanUser:input_type -> adminservice.v1.BanUserRequest
	10, // 3: adminservice.v1.AdminClient.UnbanUser:input_type -> adminservice.v1.UnbanUserRequest
	0,  // 4: adminservice.v1.AdminClient.AssignRole:input_type -> adminservice.v1.AssignRoleRequest
	2,  // 5: adminservice.v1.AdminClient.GetUser:input_type -> adminservice.v1.GetUserRequest
	5,  // 6: adminservice.v1.AdminClient.GetProfile:input_type -> adminservice.v1.GetProfileRequest
	6,  // 7: adminservice.v1.AdminClient.GetProfilesList:input_type -> adminservice.v1.GetProfilesListRequest
	9,  // 8: adminservice.v1.AdminClient.BanUser:output_type -> adminservice.v1.BanUserResponse
	11, // 9: adminservice.v1.AdminClient.UnbanUser:output_type -> adminservice.v1.UnbanUserResponse
	1,  // 10: adminservice.v1.AdminClient.AssignRole:output_type -> adminservice.v1.AssignRoleResponse
	3,  // 11: adminservice.v1.AdminClient.GetUser:output_type -> adminservice.v1.GetUserResponse
	4,  // 12: adminservice.v1.AdminClient.GetProfile:output_type -> adminservice.v1.Profile
	7,  // 13: adminservice.v1.AdminClient.GetProfilesList:output_type -> adminservice.v1.GetProfilesListResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_adminservice_presentation_grpc_proto_adminservice_proto_init() }
func file_adminservice_presentation_grpc_proto_adminservice_proto_init() {
	if File_adminservice_presentation_grpc_proto_adminservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_adminservice_presentation_grpc_proto_adminservice_proto_rawDesc), len(file_adminservice_presentation_grpc_proto_adminservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_adminservice_presentation_grpc_proto_adminservice_proto_goTypes,
		DependencyIndexes: file_adminservice_presentation_grpc_proto_adminservice_proto_depIdxs,
		MessageInfos:      file_adminservice_presentation_grpc_proto_adminservice_proto_msgTypes,
	}.Build()
	File_adminservice_presentation_grpc_proto_adminservice_proto = out.File
	file_adminservice_presentation_grpc_proto_adminservice_proto_goTypes = nil
	file_adminservice_presentation_grpc_proto_adminservice_proto_depIdxs = nil
}
