// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: userservice/presentation/grpc/proto/userservice.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Profile struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UserId               uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	PhotoId              string                 `protobuf:"bytes,4,opt,name=photo_id,json=photoId,proto3" json:"photo_id,omitempty"`
	NotificationsEnabled bool                   `protobuf:"varint,5,opt,name=notifications_enabled,json=notificationsEnabled,proto3" json:"notifications_enabled,omitempty"`
	Subscriptions        []string               `protobuf:"bytes,6,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_userservice_presentation_grpc_proto_userservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_presentation_grpc_proto_userservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_userservice_presentation_grpc_proto_userservice_proto_rawDescGZIP(), []int{0}
}

func (x *Profile) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Profile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Profile) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Profile) GetPhotoId() string {
	if x != nil {
		return x.PhotoId
	}
	return ""
}

func (x *Profile) GetNotificationsEnabled() bool {
	if x != nil {
		return x.NotificationsEnabled
	}
	return false
}

func (x *Profile) GetSubscriptions() []string {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *Profile) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type AddProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProfileRequest) Reset() {
	*x = AddProfileRequest{}
	mi := &file_userservice_presentation_grpc_proto_userservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProfileRequest) ProtoMessage() {}

func (x *AddProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_presentation_grpc_proto_userservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProfileRequest.ProtoReflect.Descriptor instead.
func (*AddProfileRequest) Descriptor() ([]byte, []int) {
	return file_userservice_presentation_grpc_proto_userservice_proto_rawDescGZIP(), []int{1}
}

func (x *AddProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddProfileRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_userservice_presentation_grpc_proto_userservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_presentation_grpc_proto_userservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_userservice_presentation_grpc_proto_userservice_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProfileRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type UploadPhotoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadPhotoRequest) Reset() {
	*x = UploadPhotoRequest{}
	mi := &file_userservice_presentation_grpc_proto_userservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadPhotoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPhotoRequest) ProtoMessage() {}

func (x *UploadPhotoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_presentation_grpc_proto_userservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPhotoRequest.ProtoReflect.Descriptor instead.
func (*UploadPhotoRequest) Descriptor() ([]byte, []int) {
	return file_userservice_presentation_grpc_proto_userservice_proto_rawDescGZIP(), []int{3}
}

func (x *UploadPhotoRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadPhotoRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadPhotoRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type ChangeSettingsRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	NotificationsEnabled bool                   `protobuf:"varint,1,opt,name=notifications_enabled,json=notificationsEnabled,proto3" json:"notifications_enabled,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ChangeSettingsRequest) Reset() {
	*x = ChangeSettingsRequest{}
	mi := &file_userservice_presentation_grpc_proto_userservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeSettingsRequest) ProtoMessage() {}

func (x *ChangeSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_presentation_grpc_proto_userservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeSettingsRequest.ProtoReflect.Descriptor instead.
func (*ChangeSettingsRequest) Descriptor() ([]byte, []int) {
	return file_userservice_presentation_grpc_proto_userservice_proto_rawDescGZIP(), []int{4}
}

func (x *ChangeSettingsRequest) GetNotificationsEnabled() bool {
	if x != nil {
		return x.NotificationsEnabled
	}
	return false
}

type ChangeSubscriptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []string               `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeSubscriptionsRequest) Reset() {
	*x = ChangeSubscriptionsRequest{}
	mi := &file_userservice_presentation_grpc_proto_userservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeSubscriptionsRequest) ProtoMessage() {}

func (x *ChangeSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_presentation_grpc_proto_userservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*ChangeSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_userservice_presentation_grpc_proto_userservice_proto_rawDescGZIP(), []int{5}
}

func (x *ChangeSubscriptionsRequest) GetSubscriptions() []string {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

var File_userservice_presentation_grpc_proto_userservice_proto protoreflect.FileDescriptor

const file_userservice_presentation_grpc_proto_userservice_proto_rawDesc = "" +
	"\n" +
	"5userservice/presentation/grpc/proto/userservice.proto\x12\x0euserservice.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xfd\x01\n" +
	"\aProfile\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x19\n" +
	"\bphoto_id\x18\x04 \x01(\tR\aphotoId\x123\n" +
	"\x15notifications_enabled\x18\x05 \x01(\bR\x14notificationsEnabled\x12$\n" +
	"\rsubscriptions\x18\x06 \x03(\tR\rsubscriptions\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"=\n" +
	"\x11AddProfileRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\"@\n" +
	"\x14UpdateProfileRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\"g\n" +
	"\x12UploadPhotoRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\"L\n" +
	"\x15ChangeSettingsRequest\x123\n" +
	"\x15notifications_enabled\x18\x01 \x01(\bR\x14notificationsEnabled\"B\n" +
	"\x1aChangeSubscriptionsRequest\x12$\n" +
	"\rsubscriptions\x18\x01 \x03(\tR\rsubscriptions2\xe1\x03\n" +
	"\fUsersService\x12H\n" +
	"\n" +
	"AddProfile\x12!.userservice.v1.AddProfileRequest\x1a\x17.userservice.v1.Profile\x12=\n" +
	"\n" +
	"GetProfile\x12\x16.google.protobuf.Empty\x1a\x17.userservice.v1.Profile\x12N\n" +
	"\rUpdateProfile\x12$.userservice.v1.UpdateProfileRequest\x1a\x17.userservice.v1.Profile\x12J\n" +
	"\vUploadPhoto\x12\".userservice.v1.UploadPhotoRequest\x1a\x17.userservice.v1.Profile\x12P\n" +
	"\x0eChangeSettings\x12%.userservice.v1.ChangeSettingsRequest\x1a\x17.userservice.v1.Profile\x12Z\n" +
	"\x13ChangeSubscriptions\x12*.userservice.v1.ChangeSubscriptionsRequest\x1a\x17.userservice.v1.ProfileB%Z#userservice/presentation/grpc/pb;pbb\x06proto3"

var (
	file_userservice_presentation_grpc_proto_userservice_proto_rawDescOnce sync.Once
	file_userservice_presentation_grpc_proto_userservice_proto_rawDescData []byte
)

func file_userservice_presentation_grpc_proto_userservice_proto_rawDescGZIP() []byte {
	file_userservice_presentation_grpc_proto_userservice_proto_rawDescOnce.Do(func() {
		file_userservice_presentation_grpc_proto_userservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_userservice_presentation_grpc_proto_userservice_proto_rawDesc), len(file_userservice_presentation_grpc_proto_userservice_proto_rawDesc)))
	})
	return file_userservice_presentation_grpc_proto_userservice_proto_rawDescData
}

var file_userservice_presentation_grpc_proto_userservice_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_userservice_presentation_grpc_proto_userservice_proto_goTypes = []any{
	(*Profile)(nil),                    // 0: userservice.v1.Profile
	(*AddProfileRequest)(nil),          // 1: userservice.v1.AddProfileRequest
	(*UpdateProfileRequest)(nil),       // 2: userservice.v1.UpdateProfileRequest
	(*UploadPhotoRequest)(nil),         // 3: userservice.v1.UploadPhotoRequest
	(*ChangeSettingsRequest)(nil),      // 4: userservice.v1.ChangeSettingsRequest
	(*ChangeSubscriptionsRequest)(nil), // 5: userservice.v1.ChangeSubscriptionsRequest
	(*timestamppb.Timestamp)(nil),      // 6: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),              // 7: google.protobuf.Empty
}
var file_userservice_presentation_grpc_proto_userservice_proto_depIdxs = []int32{
	6, // 0: userservice.v1.Profile.updated_at:type_name -> google.protobuf.Timestamp
	1, // 1: userservice.v1.UsersService.AddProfile:input_type -> userservice.v1.AddProfileRequest
	7, // 2: userservice.v1.UsersService.GetProfile:input_type -> google.protobuf.Empty
	2, // 3: userservice.v1.UsersService.UpdateProfile:input_type -> userservice.v1.UpdateProfileRequest
	3, // 4: userservice.v1.UsersService.UploadPhoto:input_type -> userservice.v1.UploadPhotoRequest
	4, // 5: userservice.v1.UsersService.ChangeSettings:input_type -> userservice.v1.ChangeSettingsRequest
	5, // 6: userservice.v1.UsersService.ChangeSubscriptions:input_type -> userservice.v1.ChangeSubscriptionsRequest
	0, // 7: userservice.v1.UsersService.AddProfile:output_type -> userservice.v1.Profile
	0, // 8: userservice.v1.UsersService.GetProfile:output_type -> userservice.v1.Profile
	0, // 9: userservice.v1.UsersService.UpdateProfile:output_type -> userservice.v1.Profile
	0, // 10: userservice.v1.UsersService.UploadPhoto:output_type -> userservice.v1.Profile
	0, // 11: userservice.v1.UsersService.ChangeSettings:output_type -> userservice.v1.Profile
	0, // 12: userservice.v1.UsersService.ChangeSubscriptions:output_type -> userservice.v1.Profile
	7, // [7:13] is the sub-list for method output_type
	1, // [1:7] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_userservice_presentation_grpc_proto_userservice_proto_init() }
func file_userservice_presentation_grpc_proto_userservice_proto_init() {
	if File_userservice_presentation_grpc_proto_userservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_userservice_presentation_grpc_proto_userservice_proto_rawDesc), len(file_userservice_presentation_grpc_proto_userservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_userservice_presentation_grpc_proto_userservice_proto_goTypes,
		DependencyIndexes: file_userservice_presentation_grpc_proto_userservice_proto_depIdxs,
		MessageInfos:      file_userservice_presentation_grpc_proto_userservice_proto_msgTypes,
	}.Build()
	File_userservice_presentation_grpc_proto_userservice_proto = out.File
	file_userservice_presentation_grpc_proto_userservice_proto_goTypes = nil
	file_userservice_presentation_grpc_proto_userservice_proto_depIdxs = nil
}
