// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: userservice.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssignRolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRolRequest) Reset() {
	*x = AssignRolRequest{}
	mi := &file_userservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRolRequest) ProtoMessage() {}

func (x *AssignRolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRolRequest.ProtoReflect.Descriptor instead.
func (*AssignRolRequest) Descriptor() ([]byte, []int) {
	return file_userservice_proto_rawDescGZIP(), []int{0}
}

func (x *AssignRolRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AssignRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Assigned      bool                   `protobuf:"varint,2,opt,name=assigned,proto3" json:"assigned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleResponse) Reset() {
	*x = AssignRoleResponse{}
	mi := &file_userservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleResponse) ProtoMessage() {}

func (x *AssignRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleResponse.ProtoReflect.Descriptor instead.
func (*AssignRoleResponse) Descriptor() ([]byte, []int) {
	return file_userservice_proto_rawDescGZIP(), []int{1}
}

func (x *AssignRoleResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AssignRoleResponse) GetAssigned() bool {
	if x != nil {
		return x.Assigned
	}
	return false
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_userservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_userservice_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_userservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_userservice_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetUserResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type Profile struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UserId               uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	PhotoId              string                 `protobuf:"bytes,4,opt,name=photo_id,json=photoId,proto3" json:"photo_id,omitempty"`
	NotificationsEnabled bool                   `protobuf:"varint,5,opt,name=notifications_enabled,json=notificationsEnabled,proto3" json:"notifications_enabled,omitempty"`
	Subscriptions        []string               `protobuf:"bytes,6,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_userservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_userservice_proto_rawDescGZIP(), []int{4}
}

func (x *Profile) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Profile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Profile) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Profile) GetPhotoId() string {
	if x != nil {
		return x.PhotoId
	}
	return ""
}

func (x *Profile) GetNotificationsEnabled() bool {
	if x != nil {
		return x.NotificationsEnabled
	}
	return false
}

func (x *Profile) GetSubscriptions() []string {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *Profile) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type AddProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProfileRequest) Reset() {
	*x = AddProfileRequest{}
	mi := &file_userservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProfileRequest) ProtoMessage() {}

func (x *AddProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProfileRequest.ProtoReflect.Descriptor instead.
func (*AddProfileRequest) Descriptor() ([]byte, []int) {
	return file_userservice_proto_rawDescGZIP(), []int{5}
}

func (x *AddProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddProfileRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_userservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_userservice_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProfileRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type UploadPhotoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadPhotoRequest) Reset() {
	*x = UploadPhotoRequest{}
	mi := &file_userservice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadPhotoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPhotoRequest) ProtoMessage() {}

func (x *UploadPhotoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPhotoRequest.ProtoReflect.Descriptor instead.
func (*UploadPhotoRequest) Descriptor() ([]byte, []int) {
	return file_userservice_proto_rawDescGZIP(), []int{7}
}

func (x *UploadPhotoRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadPhotoRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadPhotoRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type ChangeSettingsRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	NotificationsEnabled bool                   `protobuf:"varint,1,opt,name=notifications_enabled,json=notificationsEnabled,proto3" json:"notifications_enabled,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ChangeSettingsRequest) Reset() {
	*x = ChangeSettingsRequest{}
	mi := &file_userservice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeSettingsRequest) ProtoMessage() {}

func (x *ChangeSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeSettingsRequest.ProtoReflect.Descriptor instead.
func (*ChangeSettingsRequest) Descriptor() ([]byte, []int) {
	return file_userservice_proto_rawDescGZIP(), []int{8}
}

func (x *ChangeSettingsRequest) GetNotificationsEnabled() bool {
	if x != nil {
		return x.NotificationsEnabled
	}
	return false
}

type ChangeSubscriptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []string               `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeSubscriptionsRequest) Reset() {
	*x = ChangeSubscriptionsRequest{}
	mi := &file_userservice_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeSubscriptionsRequest) ProtoMessage() {}

func (x *ChangeSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*ChangeSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_userservice_proto_rawDescGZIP(), []int{9}
}

func (x *ChangeSubscriptionsRequest) GetSubscriptions() []string {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type AdminGetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminGetProfileRequest) Reset() {
	*x = AdminGetProfileRequest{}
	mi := &file_userservice_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminGetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminGetProfileRequest) ProtoMessage() {}

func (x *AdminGetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminGetProfileRequest.ProtoReflect.Descriptor instead.
func (*AdminGetProfileRequest) Descriptor() ([]byte, []int) {
	return file_userservice_proto_rawDescGZIP(), []int{10}
}

func (x *AdminGetProfileRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AdminGetProfilesListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint32                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminGetProfilesListRequest) Reset() {
	*x = AdminGetProfilesListRequest{}
	mi := &file_userservice_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminGetProfilesListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminGetProfilesListRequest) ProtoMessage() {}

func (x *AdminGetProfilesListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminGetProfilesListRequest.ProtoReflect.Descriptor instead.
func (*AdminGetProfilesListRequest) Descriptor() ([]byte, []int) {
	return file_userservice_proto_rawDescGZIP(), []int{11}
}

func (x *AdminGetProfilesListRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *AdminGetProfilesListRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type AdminGetProfilesListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*Profile             `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminGetProfilesListResponse) Reset() {
	*x = AdminGetProfilesListResponse{}
	mi := &file_userservice_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminGetProfilesListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminGetProfilesListResponse) ProtoMessage() {}

func (x *AdminGetProfilesListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminGetProfilesListResponse.ProtoReflect.Descriptor instead.
func (*AdminGetProfilesListResponse) Descriptor() ([]byte, []int) {
	return file_userservice_proto_rawDescGZIP(), []int{12}
}

func (x *AdminGetProfilesListResponse) GetProfiles() []*Profile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type AdminBanUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminBanUserRequest) Reset() {
	*x = AdminBanUserRequest{}
	mi := &file_userservice_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminBanUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminBanUserRequest) ProtoMessage() {}

func (x *AdminBanUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminBanUserRequest.ProtoReflect.Descriptor instead.
func (*AdminBanUserRequest) Descriptor() ([]byte, []int) {
	return file_userservice_proto_rawDescGZIP(), []int{13}
}

func (x *AdminBanUserRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AdminBanUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Banned        bool                   `protobuf:"varint,1,opt,name=banned,proto3" json:"banned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminBanUserResponse) Reset() {
	*x = AdminBanUserResponse{}
	mi := &file_userservice_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminBanUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminBanUserResponse) ProtoMessage() {}

func (x *AdminBanUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminBanUserResponse.ProtoReflect.Descriptor instead.
func (*AdminBanUserResponse) Descriptor() ([]byte, []int) {
	return file_userservice_proto_rawDescGZIP(), []int{14}
}

func (x *AdminBanUserResponse) GetBanned() bool {
	if x != nil {
		return x.Banned
	}
	return false
}

type AdminUnbanUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUnbanUserRequest) Reset() {
	*x = AdminUnbanUserRequest{}
	mi := &file_userservice_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUnbanUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUnbanUserRequest) ProtoMessage() {}

func (x *AdminUnbanUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUnbanUserRequest.ProtoReflect.Descriptor instead.
func (*AdminUnbanUserRequest) Descriptor() ([]byte, []int) {
	return file_userservice_proto_rawDescGZIP(), []int{15}
}

func (x *AdminUnbanUserRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AdminUnbanUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unbanned      bool                   `protobuf:"varint,1,opt,name=unbanned,proto3" json:"unbanned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUnbanUserResponse) Reset() {
	*x = AdminUnbanUserResponse{}
	mi := &file_userservice_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUnbanUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUnbanUserResponse) ProtoMessage() {}

func (x *AdminUnbanUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUnbanUserResponse.ProtoReflect.Descriptor instead.
func (*AdminUnbanUserResponse) Descriptor() ([]byte, []int) {
	return file_userservice_proto_rawDescGZIP(), []int{16}
}

func (x *AdminUnbanUserResponse) GetUnbanned() bool {
	if x != nil {
		return x.Unbanned
	}
	return false
}

var File_userservice_proto protoreflect.FileDescriptor

const file_userservice_proto_rawDesc = "" +
	"\n" +
	"\x11userservice.proto\x12\x0euserservice.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"+\n" +
	"\x10AssignRolRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"I\n" +
	"\x12AssignRoleResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1a\n" +
	"\bassigned\x18\x02 \x01(\bR\bassigned\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"T\n" +
	"\x0fGetUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"\xfd\x01\n" +
	"\aProfile\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x19\n" +
	"\bphoto_id\x18\x04 \x01(\tR\aphotoId\x123\n" +
	"\x15notifications_enabled\x18\x05 \x01(\bR\x14notificationsEnabled\x12$\n" +
	"\rsubscriptions\x18\x06 \x03(\tR\rsubscriptions\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"=\n" +
	"\x11AddProfileRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\"@\n" +
	"\x14UpdateProfileRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\"g\n" +
	"\x12UploadPhotoRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\"L\n" +
	"\x15ChangeSettingsRequest\x123\n" +
	"\x15notifications_enabled\x18\x01 \x01(\bR\x14notificationsEnabled\"B\n" +
	"\x1aChangeSubscriptionsRequest\x12$\n" +
	"\rsubscriptions\x18\x01 \x03(\tR\rsubscriptions\"1\n" +
	"\x16AdminGetProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"K\n" +
	"\x1bAdminGetProfilesListRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\rR\x06offset\"S\n" +
	"\x1cAdminGetProfilesListResponse\x123\n" +
	"\bprofiles\x18\x01 \x03(\v2\x17.userservice.v1.ProfileR\bprofiles\".\n" +
	"\x13AdminBanUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\".\n" +
	"\x14AdminBanUserResponse\x12\x16\n" +
	"\x06banned\x18\x01 \x01(\bR\x06banned\"0\n" +
	"\x15AdminUnbanUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"4\n" +
	"\x16AdminUnbanUserResponse\x12\x1a\n" +
	"\bunbanned\x18\x01 \x01(\bR\bunbanned2\x83\b\n" +
	"\vUserService\x12R\n" +
	"\n" +
	"AssignRole\x12 .userservice.v1.AssignRolRequest\x1a\".userservice.v1.AssignRoleResponse\x12J\n" +
	"\aGetUser\x12\x1e.userservice.v1.GetUserRequest\x1a\x1f.userservice.v1.GetUserResponse\x12H\n" +
	"\n" +
	"AddProfile\x12!.userservice.v1.AddProfileRequest\x1a\x17.userservice.v1.Profile\x12=\n" +
	"\n" +
	"GetProfile\x12\x16.google.protobuf.Empty\x1a\x17.userservice.v1.Profile\x12N\n" +
	"\rUpdateProfile\x12$.userservice.v1.UpdateProfileRequest\x1a\x17.userservice.v1.Profile\x12J\n" +
	"\vUploadPhoto\x12\".userservice.v1.UploadPhotoRequest\x1a\x17.userservice.v1.Profile\x12P\n" +
	"\x0eChangeSettings\x12%.userservice.v1.ChangeSettingsRequest\x1a\x17.userservice.v1.Profile\x12Z\n" +
	"\x13ChangeSubscriptions\x12*.userservice.v1.ChangeSubscriptionsRequest\x1a\x17.userservice.v1.Profile\x12Y\n" +
	"\fAdminBanUser\x12#.userservice.v1.AdminBanUserRequest\x1a$.userservice.v1.AdminBanUserResponse\x12_\n" +
	"\x0eAdminUnbanUser\x12%.userservice.v1.AdminUnbanUserRequest\x1a&.userservice.v1.AdminUnbanUserResponse\x12R\n" +
	"\x0fAdminGetProfile\x12&.userservice.v1.AdminGetProfileRequest\x1a\x17.userservice.v1.Profile\x12q\n" +
	"\x14AdminGetProfilesList\x12+.userservice.v1.AdminGetProfilesListRequest\x1a,.userservice.v1.AdminGetProfilesListResponseB0Z.AdsService/userservice/presentation/grpc/pb;pbb\x06proto3"

var (
	file_userservice_proto_rawDescOnce sync.Once
	file_userservice_proto_rawDescData []byte
)

func file_userservice_proto_rawDescGZIP() []byte {
	file_userservice_proto_rawDescOnce.Do(func() {
		file_userservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_userservice_proto_rawDesc), len(file_userservice_proto_rawDesc)))
	})
	return file_userservice_proto_rawDescData
}

var file_userservice_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_userservice_proto_goTypes = []any{
	(*AssignRolRequest)(nil),             // 0: userservice.v1.AssignRolRequest
	(*AssignRoleResponse)(nil),           // 1: userservice.v1.AssignRoleResponse
	(*GetUserRequest)(nil),               // 2: userservice.v1.GetUserRequest
	(*GetUserResponse)(nil),              // 3: userservice.v1.GetUserResponse
	(*Profile)(nil),                      // 4: userservice.v1.Profile
	(*AddProfileRequest)(nil),            // 5: userservice.v1.AddProfileRequest
	(*UpdateProfileRequest)(nil),         // 6: userservice.v1.UpdateProfileRequest
	(*UploadPhotoRequest)(nil),           // 7: userservice.v1.UploadPhotoRequest
	(*ChangeSettingsRequest)(nil),        // 8: userservice.v1.ChangeSettingsRequest
	(*ChangeSubscriptionsRequest)(nil),   // 9: userservice.v1.ChangeSubscriptionsRequest
	(*AdminGetProfileRequest)(nil),       // 10: userservice.v1.AdminGetProfileRequest
	(*AdminGetProfilesListRequest)(nil),  // 11: userservice.v1.AdminGetProfilesListRequest
	(*AdminGetProfilesListResponse)(nil), // 12: userservice.v1.AdminGetProfilesListResponse
	(*AdminBanUserRequest)(nil),          // 13: userservice.v1.AdminBanUserRequest
	(*AdminBanUserResponse)(nil),         // 14: userservice.v1.AdminBanUserResponse
	(*AdminUnbanUserRequest)(nil),        // 15: userservice.v1.AdminUnbanUserRequest
	(*AdminUnbanUserResponse)(nil),       // 16: userservice.v1.AdminUnbanUserResponse
	(*timestamppb.Timestamp)(nil),        // 17: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                // 18: google.protobuf.Empty
}
var file_userservice_proto_depIdxs = []int32{
	17, // 0: userservice.v1.Profile.updated_at:type_name -> google.protobuf.Timestamp
	4,  // 1: userservice.v1.AdminGetProfilesListResponse.profiles:type_name -> userservice.v1.Profile
	0,  // 2: userservice.v1.UserService.AssignRole:input_type -> userservice.v1.AssignRolRequest
	2,  // 3: userservice.v1.UserService.GetUser:input_type -> userservice.v1.GetUserRequest
	5,  // 4: userservice.v1.UserService.AddProfile:input_type -> userservice.v1.AddProfileRequest
	18, // 5: userservice.v1.UserService.GetProfile:input_type -> google.protobuf.Empty
	6,  // 6: userservice.v1.UserService.UpdateProfile:input_type -> userservice.v1.UpdateProfileRequest
	7,  // 7: userservice.v1.UserService.UploadPhoto:input_type -> userservice.v1.UploadPhotoRequest
	8,  // 8: userservice.v1.UserService.ChangeSettings:input_type -> userservice.v1.ChangeSettingsRequest
	9,  // 9: userservice.v1.UserService.ChangeSubscriptions:input_type -> userservice.v1.ChangeSubscriptionsRequest
	13, // 10: userservice.v1.UserService.AdminBanUser:input_type -> userservice.v1.AdminBanUserRequest
	15, // 11: userservice.v1.UserService.AdminUnbanUser:input_type -> userservice.v1.AdminUnbanUserRequest
	10, // 12: userservice.v1.UserService.AdminGetProfile:input_type -> userservice.v1.AdminGetProfileRequest
	11, // 13: userservice.v1.UserService.AdminGetProfilesList:input_type -> userservice.v1.AdminGetProfilesListRequest
	1,  // 14: userservice.v1.UserService.AssignRole:output_type -> userservice.v1.AssignRoleResponse
	3,  // 15: userservice.v1.UserService.GetUser:output_type -> userservice.v1.GetUserResponse
	4,  // 16: userservice.v1.UserService.AddProfile:output_type -> userservice.v1.Profile
	4,  // 17: userservice.v1.UserService.GetProfile:output_type -> userservice.v1.Profile
	4,  // 18: userservice.v1.UserService.UpdateProfile:output_type -> userservice.v1.Profile
	4,  // 19: userservice.v1.UserService.UploadPhoto:output_type -> userservice.v1.Profile
	4,  // 20: userservice.v1.UserService.ChangeSettings:output_type -> userservice.v1.Profile
	4,  // 21: userservice.v1.UserService.ChangeSubscriptions:output_type -> userservice.v1.Profile
	14, // 22: userservice.v1.UserService.AdminBanUser:output_type -> userservice.v1.AdminBanUserResponse
	16, // 23: userservice.v1.UserService.AdminUnbanUser:output_type -> userservice.v1.AdminUnbanUserResponse
	4,  // 24: userservice.v1.UserService.AdminGetProfile:output_type -> userservice.v1.Profile
	12, // 25: userservice.v1.UserService.AdminGetProfilesList:output_type -> userservice.v1.AdminGetProfilesListResponse
	14, // [14:26] is the sub-list for method output_type
	2,  // [2:14] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_userservice_proto_init() }
func file_userservice_proto_init() {
	if File_userservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_userservice_proto_rawDesc), len(file_userservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_userservice_proto_goTypes,
		DependencyIndexes: file_userservice_proto_depIdxs,
		MessageInfos:      file_userservice_proto_msgTypes,
	}.Build()
	File_userservice_proto = out.File
	file_userservice_proto_goTypes = nil
	file_userservice_proto_depIdxs = nil
}
