// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: userservice.proto

package userservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Profile struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UserId               uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	PhotoId              string                 `protobuf:"bytes,4,opt,name=photo_id,json=photoId,proto3" json:"photo_id,omitempty"`
	NotificationsEnabled bool                   `protobuf:"varint,5,opt,name=notifications_enabled,json=notificationsEnabled,proto3" json:"notifications_enabled,omitempty"`
	Subscriptions        []string               `protobuf:"bytes,6,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_userservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_userservice_proto_rawDescGZIP(), []int{0}
}

func (x *Profile) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Profile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Profile) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Profile) GetPhotoId() string {
	if x != nil {
		return x.PhotoId
	}
	return ""
}

func (x *Profile) GetNotificationsEnabled() bool {
	if x != nil {
		return x.NotificationsEnabled
	}
	return false
}

func (x *Profile) GetSubscriptions() []string {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *Profile) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type AddProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProfileRequest) Reset() {
	*x = AddProfileRequest{}
	mi := &file_userservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProfileRequest) ProtoMessage() {}

func (x *AddProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProfileRequest.ProtoReflect.Descriptor instead.
func (*AddProfileRequest) Descriptor() ([]byte, []int) {
	return file_userservice_proto_rawDescGZIP(), []int{1}
}

func (x *AddProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddProfileRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_userservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_userservice_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProfileRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type UploadPhotoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadPhotoRequest) Reset() {
	*x = UploadPhotoRequest{}
	mi := &file_userservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadPhotoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPhotoRequest) ProtoMessage() {}

func (x *UploadPhotoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPhotoRequest.ProtoReflect.Descriptor instead.
func (*UploadPhotoRequest) Descriptor() ([]byte, []int) {
	return file_userservice_proto_rawDescGZIP(), []int{3}
}

func (x *UploadPhotoRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadPhotoRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadPhotoRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type ChangeSettingsRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	NotificationsEnabled bool                   `protobuf:"varint,1,opt,name=notifications_enabled,json=notificationsEnabled,proto3" json:"notifications_enabled,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ChangeSettingsRequest) Reset() {
	*x = ChangeSettingsRequest{}
	mi := &file_userservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeSettingsRequest) ProtoMessage() {}

func (x *ChangeSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeSettingsRequest.ProtoReflect.Descriptor instead.
func (*ChangeSettingsRequest) Descriptor() ([]byte, []int) {
	return file_userservice_proto_rawDescGZIP(), []int{4}
}

func (x *ChangeSettingsRequest) GetNotificationsEnabled() bool {
	if x != nil {
		return x.NotificationsEnabled
	}
	return false
}

type ChangeSubscriptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []string               `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeSubscriptionsRequest) Reset() {
	*x = ChangeSubscriptionsRequest{}
	mi := &file_userservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeSubscriptionsRequest) ProtoMessage() {}

func (x *ChangeSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*ChangeSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_userservice_proto_rawDescGZIP(), []int{5}
}

func (x *ChangeSubscriptionsRequest) GetSubscriptions() []string {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type ChangeSubscriptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeSubscriptionsResponse) Reset() {
	*x = ChangeSubscriptionsResponse{}
	mi := &file_userservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeSubscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeSubscriptionsResponse) ProtoMessage() {}

func (x *ChangeSubscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeSubscriptionsResponse.ProtoReflect.Descriptor instead.
func (*ChangeSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_userservice_proto_rawDescGZIP(), []int{6}
}

func (x *ChangeSubscriptionsResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type AdminGetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminGetProfileRequest) Reset() {
	*x = AdminGetProfileRequest{}
	mi := &file_userservice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminGetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminGetProfileRequest) ProtoMessage() {}

func (x *AdminGetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminGetProfileRequest.ProtoReflect.Descriptor instead.
func (*AdminGetProfileRequest) Descriptor() ([]byte, []int) {
	return file_userservice_proto_rawDescGZIP(), []int{7}
}

func (x *AdminGetProfileRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AdminGetProfilesListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint32                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminGetProfilesListRequest) Reset() {
	*x = AdminGetProfilesListRequest{}
	mi := &file_userservice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminGetProfilesListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminGetProfilesListRequest) ProtoMessage() {}

func (x *AdminGetProfilesListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminGetProfilesListRequest.ProtoReflect.Descriptor instead.
func (*AdminGetProfilesListRequest) Descriptor() ([]byte, []int) {
	return file_userservice_proto_rawDescGZIP(), []int{8}
}

func (x *AdminGetProfilesListRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *AdminGetProfilesListRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type AdminGetProfilesListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*Profile             `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminGetProfilesListResponse) Reset() {
	*x = AdminGetProfilesListResponse{}
	mi := &file_userservice_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminGetProfilesListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminGetProfilesListResponse) ProtoMessage() {}

func (x *AdminGetProfilesListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminGetProfilesListResponse.ProtoReflect.Descriptor instead.
func (*AdminGetProfilesListResponse) Descriptor() ([]byte, []int) {
	return file_userservice_proto_rawDescGZIP(), []int{9}
}

func (x *AdminGetProfilesListResponse) GetProfiles() []*Profile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type AdminBanUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminBanUserRequest) Reset() {
	*x = AdminBanUserRequest{}
	mi := &file_userservice_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminBanUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminBanUserRequest) ProtoMessage() {}

func (x *AdminBanUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminBanUserRequest.ProtoReflect.Descriptor instead.
func (*AdminBanUserRequest) Descriptor() ([]byte, []int) {
	return file_userservice_proto_rawDescGZIP(), []int{10}
}

func (x *AdminBanUserRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AdminBanUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Banned        bool                   `protobuf:"varint,1,opt,name=banned,proto3" json:"banned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminBanUserResponse) Reset() {
	*x = AdminBanUserResponse{}
	mi := &file_userservice_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminBanUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminBanUserResponse) ProtoMessage() {}

func (x *AdminBanUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminBanUserResponse.ProtoReflect.Descriptor instead.
func (*AdminBanUserResponse) Descriptor() ([]byte, []int) {
	return file_userservice_proto_rawDescGZIP(), []int{11}
}

func (x *AdminBanUserResponse) GetBanned() bool {
	if x != nil {
		return x.Banned
	}
	return false
}

type AdminUnbanUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUnbanUserRequest) Reset() {
	*x = AdminUnbanUserRequest{}
	mi := &file_userservice_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUnbanUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUnbanUserRequest) ProtoMessage() {}

func (x *AdminUnbanUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUnbanUserRequest.ProtoReflect.Descriptor instead.
func (*AdminUnbanUserRequest) Descriptor() ([]byte, []int) {
	return file_userservice_proto_rawDescGZIP(), []int{12}
}

func (x *AdminUnbanUserRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AdminUnbanUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unbanned      bool                   `protobuf:"varint,1,opt,name=unbanned,proto3" json:"unbanned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUnbanUserResponse) Reset() {
	*x = AdminUnbanUserResponse{}
	mi := &file_userservice_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUnbanUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUnbanUserResponse) ProtoMessage() {}

func (x *AdminUnbanUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUnbanUserResponse.ProtoReflect.Descriptor instead.
func (*AdminUnbanUserResponse) Descriptor() ([]byte, []int) {
	return file_userservice_proto_rawDescGZIP(), []int{13}
}

func (x *AdminUnbanUserResponse) GetUnbanned() bool {
	if x != nil {
		return x.Unbanned
	}
	return false
}

var File_userservice_proto protoreflect.FileDescriptor

const file_userservice_proto_rawDesc = "" +
	"\n" +
	"\x11userservice.proto\x12\vuserservice\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xfd\x01\n" +
	"\aProfile\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x19\n" +
	"\bphoto_id\x18\x04 \x01(\tR\aphotoId\x123\n" +
	"\x15notifications_enabled\x18\x05 \x01(\bR\x14notificationsEnabled\x12$\n" +
	"\rsubscriptions\x18\x06 \x03(\tR\rsubscriptions\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"=\n" +
	"\x11AddProfileRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\"@\n" +
	"\x14UpdateProfileRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\"g\n" +
	"\x12UploadPhotoRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\"L\n" +
	"\x15ChangeSettingsRequest\x123\n" +
	"\x15notifications_enabled\x18\x01 \x01(\bR\x14notificationsEnabled\"B\n" +
	"\x1aChangeSubscriptionsRequest\x12$\n" +
	"\rsubscriptions\x18\x01 \x03(\tR\rsubscriptions\"M\n" +
	"\x1bChangeSubscriptionsResponse\x12.\n" +
	"\aprofile\x18\x01 \x01(\v2\x14.userservice.ProfileR\aprofile\"1\n" +
	"\x16AdminGetProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"K\n" +
	"\x1bAdminGetProfilesListRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\rR\x06offset\"P\n" +
	"\x1cAdminGetProfilesListResponse\x120\n" +
	"\bprofiles\x18\x01 \x03(\v2\x14.userservice.ProfileR\bprofiles\".\n" +
	"\x13AdminBanUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\".\n" +
	"\x14AdminBanUserResponse\x12\x16\n" +
	"\x06banned\x18\x01 \x01(\bR\x06banned\"0\n" +
	"\x15AdminUnbanUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"4\n" +
	"\x16AdminUnbanUserResponse\x12\x1a\n" +
	"\bunbanned\x18\x01 \x01(\bR\bunbanned2\xbe\x06\n" +
	"\vUserService\x12B\n" +
	"\n" +
	"AddProfile\x12\x1e.userservice.AddProfileRequest\x1a\x14.userservice.Profile\x12:\n" +
	"\n" +
	"GetProfile\x12\x16.google.protobuf.Empty\x1a\x14.userservice.Profile\x12H\n" +
	"\rUpdateProfile\x12!.userservice.UpdateProfileRequest\x1a\x14.userservice.Profile\x12D\n" +
	"\vUploadPhoto\x12\x1f.userservice.UploadPhotoRequest\x1a\x14.userservice.Profile\x12J\n" +
	"\x0eChangeSettings\x12\".userservice.ChangeSettingsRequest\x1a\x14.userservice.Profile\x12h\n" +
	"\x13ChangeSubscriptions\x12'.userservice.ChangeSubscriptionsRequest\x1a(.userservice.ChangeSubscriptionsResponse\x12L\n" +
	"\x0fAdminGetProfile\x12#.userservice.AdminGetProfileRequest\x1a\x14.userservice.Profile\x12k\n" +
	"\x14AdminGetProfilesList\x12(.userservice.AdminGetProfilesListRequest\x1a).userservice.AdminGetProfilesListResponse\x12S\n" +
	"\fAdminBanUser\x12 .userservice.AdminBanUserRequest\x1a!.userservice.AdminBanUserResponse\x12Y\n" +
	"\x0eAdminUnbanUser\x12\".userservice.AdminUnbanUserRequest\x1a#.userservice.AdminUnbanUserResponseB*Z(AdsService/userservice/proto;userserviceb\x06proto3"

var (
	file_userservice_proto_rawDescOnce sync.Once
	file_userservice_proto_rawDescData []byte
)

func file_userservice_proto_rawDescGZIP() []byte {
	file_userservice_proto_rawDescOnce.Do(func() {
		file_userservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_userservice_proto_rawDesc), len(file_userservice_proto_rawDesc)))
	})
	return file_userservice_proto_rawDescData
}

var file_userservice_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_userservice_proto_goTypes = []any{
	(*Profile)(nil),                      // 0: userservice.Profile
	(*AddProfileRequest)(nil),            // 1: userservice.AddProfileRequest
	(*UpdateProfileRequest)(nil),         // 2: userservice.UpdateProfileRequest
	(*UploadPhotoRequest)(nil),           // 3: userservice.UploadPhotoRequest
	(*ChangeSettingsRequest)(nil),        // 4: userservice.ChangeSettingsRequest
	(*ChangeSubscriptionsRequest)(nil),   // 5: userservice.ChangeSubscriptionsRequest
	(*ChangeSubscriptionsResponse)(nil),  // 6: userservice.ChangeSubscriptionsResponse
	(*AdminGetProfileRequest)(nil),       // 7: userservice.AdminGetProfileRequest
	(*AdminGetProfilesListRequest)(nil),  // 8: userservice.AdminGetProfilesListRequest
	(*AdminGetProfilesListResponse)(nil), // 9: userservice.AdminGetProfilesListResponse
	(*AdminBanUserRequest)(nil),          // 10: userservice.AdminBanUserRequest
	(*AdminBanUserResponse)(nil),         // 11: userservice.AdminBanUserResponse
	(*AdminUnbanUserRequest)(nil),        // 12: userservice.AdminUnbanUserRequest
	(*AdminUnbanUserResponse)(nil),       // 13: userservice.AdminUnbanUserResponse
	(*timestamppb.Timestamp)(nil),        // 14: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                // 15: google.protobuf.Empty
}
var file_userservice_proto_depIdxs = []int32{
	14, // 0: userservice.Profile.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 1: userservice.ChangeSubscriptionsResponse.profile:type_name -> userservice.Profile
	0,  // 2: userservice.AdminGetProfilesListResponse.profiles:type_name -> userservice.Profile
	1,  // 3: userservice.UserService.AddProfile:input_type -> userservice.AddProfileRequest
	15, // 4: userservice.UserService.GetProfile:input_type -> google.protobuf.Empty
	2,  // 5: userservice.UserService.UpdateProfile:input_type -> userservice.UpdateProfileRequest
	3,  // 6: userservice.UserService.UploadPhoto:input_type -> userservice.UploadPhotoRequest
	4,  // 7: userservice.UserService.ChangeSettings:input_type -> userservice.ChangeSettingsRequest
	5,  // 8: userservice.UserService.ChangeSubscriptions:input_type -> userservice.ChangeSubscriptionsRequest
	7,  // 9: userservice.UserService.AdminGetProfile:input_type -> userservice.AdminGetProfileRequest
	8,  // 10: userservice.UserService.AdminGetProfilesList:input_type -> userservice.AdminGetProfilesListRequest
	10, // 11: userservice.UserService.AdminBanUser:input_type -> userservice.AdminBanUserRequest
	12, // 12: userservice.UserService.AdminUnbanUser:input_type -> userservice.AdminUnbanUserRequest
	0,  // 13: userservice.UserService.AddProfile:output_type -> userservice.Profile
	0,  // 14: userservice.UserService.GetProfile:output_type -> userservice.Profile
	0,  // 15: userservice.UserService.UpdateProfile:output_type -> userservice.Profile
	0,  // 16: userservice.UserService.UploadPhoto:output_type -> userservice.Profile
	0,  // 17: userservice.UserService.ChangeSettings:output_type -> userservice.Profile
	6,  // 18: userservice.UserService.ChangeSubscriptions:output_type -> userservice.ChangeSubscriptionsResponse
	0,  // 19: userservice.UserService.AdminGetProfile:output_type -> userservice.Profile
	9,  // 20: userservice.UserService.AdminGetProfilesList:output_type -> userservice.AdminGetProfilesListResponse
	11, // 21: userservice.UserService.AdminBanUser:output_type -> userservice.AdminBanUserResponse
	13, // 22: userservice.UserService.AdminUnbanUser:output_type -> userservice.AdminUnbanUserResponse
	13, // [13:23] is the sub-list for method output_type
	3,  // [3:13] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_userservice_proto_init() }
func file_userservice_proto_init() {
	if File_userservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_userservice_proto_rawDesc), len(file_userservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_userservice_proto_goTypes,
		DependencyIndexes: file_userservice_proto_depIdxs,
		MessageInfos:      file_userservice_proto_msgTypes,
	}.Build()
	File_userservice_proto = out.File
	file_userservice_proto_goTypes = nil
	file_userservice_proto_depIdxs = nil
}
