package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"ads/authservice/internal/generated/auth_v1"
	"ads/userservice/internal/generated/user_v1"
	"context"
	"fmt"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, email string, password string) (string, error) {
	panic(fmt.Errorf("not implemented: Register - register"))
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string, ip *string, userAgent *string) (*auth_v1.LoginResponse, error) {
	panic(fmt.Errorf("not implemented: Login - login"))
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context, refreshToken string) (bool, error) {
	panic(fmt.Errorf("not implemented: Logout - logout"))
}

// RefreshSession is the resolver for the refreshSession field.
func (r *mutationResolver) RefreshSession(ctx context.Context, oldRefreshToken string, ip *string, userAgent *string) (*auth_v1.LoginResponse, error) {
	panic(fmt.Errorf("not implemented: RefreshSession - refreshSession"))
}

// AssignRole is the resolver for the assignRole field.
func (r *mutationResolver) AssignRole(ctx context.Context, accountID string, role string) (bool, error) {
	panic(fmt.Errorf("not implemented: AssignRole - assignRole"))
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, firstName *string, lastName *string, phone *string, avatarURL *string, bio *string) (bool, error) {
	panic(fmt.Errorf("not implemented: UpdateProfile - updateProfile"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*user_v1.GetProfileResponse, error) {
	panic(fmt.Errorf("not implemented: Me - me"))
}

// ID is the resolver for the id field.
func (r *userResolver) ID(ctx context.Context, obj *user_v1.GetProfileResponse) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// Role is the resolver for the role field.
func (r *userResolver) Role(ctx context.Context, obj *user_v1.GetProfileResponse) (*string, error) {
	panic(fmt.Errorf("not implemented: Role - role"))
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *userResolver) UpdatedAt(ctx context.Context, obj *user_v1.GetProfileResponse) (*string, error) {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
}
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	panic(fmt.Errorf("not implemented: Todos - todos"))
}
*/
