package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"ads/pkg/generated/auth_v1"
	"ads/pkg/generated/user_v1"
	"ads/pkg/utils"
	"context"
	"fmt"
	"time"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, email string, password string) (string, error) {
	resp, err := r.AuthClient.Register(ctx, &auth_v1.RegisterRequest{
		Email:    email,
		Password: password,
	})
	if err != nil {
		return "", err
	}
	return resp.GetAccountId(), nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string, ip *string, userAgent *string) (*auth_v1.LoginResponse, error) {
	resp, err := r.AuthClient.Login(ctx, &auth_v1.LoginRequest{
		Email:     email,
		Password:  password,
		Ip:        ip,
		UserAgent: userAgent,
	})
	if err != nil {
		return nil, err
	}
	return &auth_v1.LoginResponse{
		AccessToken:  resp.GetAccessToken(),
		RefreshToken: resp.GetRefreshToken(),
	}, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context, refreshToken string) (bool, error) {
	resp, err := r.AuthClient.Logout(
		ctx, &auth_v1.LogoutRequest{RefreshToken: refreshToken},
	)
	if err != nil {
		return false, err
	}
	return resp.GetLogout(), nil
}

// RefreshSession is the resolver for the refreshSession field.
func (r *mutationResolver) RefreshSession(ctx context.Context, oldRefreshToken string, ip *string, userAgent *string) (*auth_v1.RefreshSessionResponse, error) {
	resp, err := r.AuthClient.RefreshSession(ctx, &auth_v1.RefreshSessionRequest{
		OldRefreshToken: oldRefreshToken,
		Ip:              ip,
		UserAgent:       userAgent,
	})
	if err != nil {
		return nil, err
	}
	return &auth_v1.RefreshSessionResponse{
		AccessToken:  resp.GetAccessToken(),
		RefreshToken: resp.GetRefreshToken(),
	}, nil
}

// AssignRole is the resolver for the assignRole field.
func (r *mutationResolver) AssignRole(ctx context.Context, accountID string, role string) (bool, error) {
	resp, err := r.AuthClient.AssignRole(ctx, &auth_v1.AssignRoleRequest{
		AccountId: accountID,
		Role:      role,
	})
	if err != nil {
		return false, err
	}
	return resp.GetAssign(), nil
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, firstName *string, lastName *string, phone *string, avatarURL *string, bio *string) (bool, error) {
	idVal := ctx.Value(utils.AccountIDKey)
	if idVal == nil {
		return false, fmt.Errorf("unauthorized")
	}
	accountID := idVal.(string)

	outCtx := utils.PackAccountIDForGRPC(ctx, accountID)

	resp, err := r.UserClient.UpdateProfile(outCtx, &user_v1.UpdateProfileRequest{
		FirstName: firstName,
		LastName:  lastName,
		Phone:     phone,
		AvatarUrl: avatarURL,
		Bio:       bio,
	})
	if err != nil {
		return false, err
	}

	return resp.GetSuccess(), nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*user_v1.GetProfileResponse, error) {
	idVal := ctx.Value(utils.AccountIDKey)
	if idVal == nil {
		return nil, fmt.Errorf("unauthorized")
	}
	accountID := idVal.(string)

	outCtx := utils.PackAccountIDForGRPC(ctx, accountID)

	return r.UserClient.GetProfile(outCtx, &user_v1.GetProfileRequest{})
}

// ID is the resolver for the id field.
func (r *userResolver) ID(ctx context.Context, obj *user_v1.GetProfileResponse) (string, error) {
	return obj.GetAccountId(), nil
}

// Role is the resolver for the role field.
func (r *userResolver) Role(ctx context.Context, obj *user_v1.GetProfileResponse) (*string, error) {
	roleVal := ctx.Value(utils.RoleKey)
	if roleVal == nil {
		return nil, nil
	}
	role := roleVal.(string)
	return &role, nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *userResolver) UpdatedAt(ctx context.Context, obj *user_v1.GetProfileResponse) (*string, error) {
	if obj.GetUpdatedAt() == nil {
		return nil, nil
	}
	t := obj.GetUpdatedAt().AsTime().Format(time.RFC3339)
	return &t, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
