// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package resolvers

import (
	"time"
)

type AdminBanResult struct {
	Banned bool `json:"banned"`
}

type AdminUnbanResult struct {
	Unbanned bool `json:"unbanned"`
}

type AssignRoleResult struct {
	UserID   string `json:"user_id"`
	Assigned bool   `json:"assigned"`
}

type AuthPayload struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

type ChangeSettingsInput struct {
	NotificationsEnabled bool `json:"notifications_enabled"`
}

type ChangeSubscriptionsInput struct {
	Subscriptions []string `json:"subscriptions"`
}

type Mutation struct {
}

type ProfilesList struct {
	Profiles []*UserProfile `json:"profiles"`
}

type Query struct {
}

type UpdateProfileInput struct {
	Name  *string `json:"name,omitempty"`
	Phone *string `json:"phone,omitempty"`
}

type User struct {
	UserID string `json:"user_id"`
	Email  string `json:"email"`
	Role   string `json:"role"`
}

type UserProfile struct {
	UserID               string     `json:"user_id"`
	Name                 *string    `json:"name,omitempty"`
	Phone                *string    `json:"phone,omitempty"`
	PhotoID              *string    `json:"photo_id,omitempty"`
	NotificationsEnabled bool       `json:"notifications_enabled"`
	Subscriptions        []string   `json:"subscriptions"`
	UpdatedAt            *time.Time `json:"updated_at,omitempty"`
}
