package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	authpb "AdsService/authservice/presentation/grpc/pb"
	userpb "AdsService/userservice/presentation/grpc/pb"
	"context"
	"fmt"
	"google.golang.org/protobuf/types/known/emptypb"
	"io"
	"strconv"

	"github.com/99designs/gqlgen/graphql"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, email string, password string) (*AuthPayload, error) {
	resp, err := r.AuthClient.Register(ctx, &authpb.RegisterRequest{
		Email:    email,
		Password: password,
	})
	if err != nil {
		return nil, err
	}

	return MapPbAuthResponseToAuthPayload(resp), nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*AuthPayload, error) {
	resp, err := r.AuthClient.Login(ctx, &authpb.LoginRequest{
		Email:    email,
		Password: password,
	})
	if err != nil {
		return nil, err
	}

	return MapPbAuthResponseToAuthPayload(resp), nil
}

// AddProfile is the resolver for the addProfile field.
func (r *mutationResolver) AddProfile(ctx context.Context, name string, phone string) (*UserProfile, error) {
	resp, err := r.UserClient.AddProfile(ctx, &userpb.AddProfileRequest{
		Name:  name,
		Phone: phone,
	})
	if err != nil {
		return nil, err
	}

	return MapPbProfileToUserProfile(resp), nil
}

func (r *mutationResolver) GetProfile(ctx context.Context, input *emptypb.Empty) (*UserProfile, error) {
	resp, err := r.UserClient.GetProfile(ctx, input)
	if err != nil {
		return nil, err
	}

	return MapPbProfileToUserProfile(resp), nil
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input UpdateProfileInput) (*UserProfile, error) {
	resp, err := r.UserClient.UpdateProfile(ctx, &userpb.UpdateProfileRequest{
		Name:  *input.Name,
		Phone: *input.Phone,
	})
	if err != nil {
		return nil, err
	}

	return MapPbProfileToUserProfile(resp), nil
}

// UploadMyPhoto is the resolver for the uploadMyPhoto field.
func (r *mutationResolver) UploadMyPhoto(ctx context.Context, file graphql.Upload) (string, error) {
	data, err := io.ReadAll(file.File)
	if err != nil {
		return "", fmt.Errorf("failed to read upload file: %w", err)
	}

	resp, err := r.UserClient.UploadPhoto(ctx, &userpb.UploadPhotoRequest{
		Data:        data,
		Filename:    file.Filename,
		ContentType: file.ContentType,
	})
	if err != nil {
		return "", fmt.Errorf("failed to upload photo: %w", err)
	}

	return resp.PhotoId, nil
}

// ChangeSettings is the resolver for the changeSettings field.
func (r *mutationResolver) ChangeSettings(ctx context.Context, input ChangeSettingsInput) (*UserProfile, error) {
	resp, err := r.UserClient.ChangeSettings(ctx, &userpb.ChangeSettingsRequest{NotificationsEnabled: input.NotificationsEnabled})
	if err != nil {
		return nil, err
	}

	return MapPbProfileToUserProfile(resp), nil
}

// ChangeSubscriptions is the resolver for the changeSubscriptions field.
func (r *mutationResolver) ChangeSubscriptions(ctx context.Context, input ChangeSubscriptionsInput) (*UserProfile, error) {
	resp, err := r.UserClient.ChangeSubscriptions(ctx, &userpb.ChangeSubscriptionsRequest{Subscriptions: input.Subscriptions})
	if err != nil {
		return nil, err
	}

	return MapPbProfileToUserProfile(resp), nil
}

// AssignUserAsAdmin is the resolver for the assignUserAsAdmin field.
func (r *mutationResolver) AssignUserAsAdmin(ctx context.Context, userID string) (*AssignRoleResult, error) {
	id, err := strconv.ParseUint(userID, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid user_id: %w", err)
	}

	resp, err := r.UserClient.AssignRole(ctx, &userpb.AssignRolRequest{UserId: id})
	if err != nil {
		return nil, err
	}

	return MapPbAssignRoleResponseToAssignRoleResult(resp), nil
}

// AdminBanUser is the resolver for the adminBanUser field.
func (r *mutationResolver) AdminBanUser(ctx context.Context, userID string) (*AdminBanResult, error) {
	id, err := strconv.ParseUint(userID, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid user_id: %w", err)
	}

	resp, err := r.UserClient.AdminBanUser(ctx, &userpb.AdminBanUserRequest{UserId: id})
	if err != nil {
		return nil, err
	}

	return MapPbBanResponseToBanResult(resp), nil
}

// AdminUnbanUser is the resolver for the adminUnbanUser field.
func (r *mutationResolver) AdminUnbanUser(ctx context.Context, userID string) (*AdminUnbanResult, error) {
	id, err := strconv.ParseUint(userID, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid user_id: %w", err)
	}

	resp, err := r.UserClient.AdminUnbanUser(ctx, &userpb.AdminUnbanUserRequest{UserId: id})
	if err != nil {
		return nil, err
	}

	return MapPbUnbanResponseToUnbanResult(resp), nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*UserProfile, error) {
	resp, err := r.Resolver.UserClient.GetProfile(ctx, &emptypb.Empty{})
	if err != nil {
		return nil, err
	}

	return MapPbProfileToUserProfile(resp), nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, userID string) (*User, error) {
	// конвертим string → uint64
	id, err := strconv.ParseUint(userID, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid user_id: %w", err)
	}

	resp, err := r.Resolver.UserClient.GetUser(ctx, &userpb.GetUserRequest{UserId: id})
	if err != nil {
		return nil, err
	}

	return MapPbGetUserResponseToUser(resp), nil
}

// AdminGetProfile is the resolver for the adminGetProfile field.
func (r *queryResolver) AdminGetProfile(ctx context.Context, userID string) (*UserProfile, error) {
	id, err := strconv.ParseUint(userID, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid user_id: %w", err)
	}

	resp, err := r.Resolver.UserClient.AdminGetProfile(ctx, &userpb.AdminGetProfileRequest{UserId: id})
	if err != nil {
		return nil, err
	}

	return MapPbProfileToUserProfile(resp), nil
}

// AdminGetProfiles is the resolver for the adminGetProfiles field.
func (r *queryResolver) AdminGetProfiles(ctx context.Context, limit int, offset int) (*ProfilesList, error) {
	resp, err := r.Resolver.UserClient.AdminGetProfilesList(ctx, &userpb.AdminGetProfilesListRequest{
		Limit:  uint32(limit),
		Offset: uint32(offset),
	})
	if err != nil {
		return nil, err
	}

	return MapPbProfilesToUserProfiles(resp), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
