package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	adminpb "ads/adminservice/presentation/grpc/pb"
	authpb "ads/authservice/presentation/grpc/pb"
	userpb "ads/userservice/presentation/grpc/pb"
	"context"
	"fmt"
	"io"
	"strconv"

	"github.com/99designs/gqlgen/graphql"
	"google.golang.org/protobuf/types/known/emptypb"
)

// RegisterUser is the resolver for the registerUser field.
func (r *mutationResolver) RegisterUser(ctx context.Context, input *RegisterUserInput) (*RegisterUserOutput, error) {
	resp, err := r.AuthClient.Register(ctx, &authpb.RegisterRequest{
		Email:    input.Email,
		Password: input.Password,
	})

	if err != nil {
		return nil, err
	}

	return MapPbAuthResponseToRegisterOutput(resp), nil
}

// LoginUser is the resolver for the loginUser field.
func (r *mutationResolver) LoginUser(ctx context.Context, input *LoginUserInput) (*LoginUserOutput, error) {
	resp, err := r.AuthClient.Login(ctx, &authpb.LoginRequest{
		Email:    input.Email,
		Password: input.Password,
	})

	if err != nil {
		return nil, err
	}

	return MapPbAuthResponseToLoginOutput(resp), nil
}

// AddProfile is the resolver for the addProfile field.
func (r *mutationResolver) AddProfile(ctx context.Context, input AddProfileInput) (*UserProfile, error) {
	resp, err := r.UserClient.AddProfile(ctx, &userpb.AddProfileRequest{
		Name:  input.Name,
		Phone: input.Phone,
	})
	if err != nil {
		return nil, err
	}

	return MapUserPbProfileToUserProfile(resp), nil
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input UpdateProfileInput) (*UserProfile, error) {
	resp, err := r.UserClient.UpdateProfile(ctx, &userpb.UpdateProfileRequest{
		Name:  *input.Name,
		Phone: *input.Phone,
	})
	if err != nil {
		return nil, err
	}

	return MapUserPbProfileToUserProfile(resp), nil
}

// UploadMyPhoto is the resolver for the uploadMyPhoto field.
func (r *mutationResolver) UploadMyPhoto(ctx context.Context, file graphql.Upload) (*UserProfile, error) {
	data, err := io.ReadAll(file.File)
	if err != nil {
		return nil, fmt.Errorf("failed to read upload file: %w", err)
	}

	resp, err := r.UserClient.UploadPhoto(ctx, &userpb.UploadPhotoRequest{
		Data:        data,
		Filename:    file.Filename,
		ContentType: file.ContentType,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to upload photo: %w", err)
	}

	return MapUserPbProfileToUserProfile(resp), nil
}

// ChangeSettings is the resolver for the changeSettings field.
func (r *mutationResolver) ChangeSettings(ctx context.Context, input ChangeSettingsInput) (*UserProfile, error) {
	resp, err := r.UserClient.ChangeSettings(ctx, &userpb.ChangeSettingsRequest{NotificationsEnabled: input.NotificationsEnabled})
	if err != nil {
		return nil, err
	}

	return MapUserPbProfileToUserProfile(resp), nil
}

// ChangeSubscriptions is the resolver for the changeSubscriptions field.
func (r *mutationResolver) ChangeSubscriptions(ctx context.Context, input ChangeSubscriptionsInput) (*UserProfile, error) {
	resp, err := r.UserClient.ChangeSubscriptions(ctx, &userpb.ChangeSubscriptionsRequest{Subscriptions: input.Subscriptions})
	if err != nil {
		return nil, err
	}

	return MapUserPbProfileToUserProfile(resp), nil
}

// AssignUserAsAdmin is the resolver for the assignUserAsAdmin field.
func (r *mutationResolver) AssignUserAsAdmin(ctx context.Context, input *AssignRoleInput) (*AssignRoleOutput, error) {
	n, err := strconv.ParseUint(input.UserID, 10, 64)
	if err != nil {
		return &AssignRoleOutput{
			UserID:   input.UserID,
			Assigned: false,
		}, err
	}

	resp, err := r.AdminClient.AssignRole(ctx, &adminpb.AssignRoleRequest{UserId: n})

	if err != nil {
		return &AssignRoleOutput{
			UserID:   input.UserID,
			Assigned: false,
		}, err
	}

	return MapPbAssignRoleResponseToAssignRoleOutput(resp), nil
}

// AdminBanUser is the resolver for the adminBanUser field.
func (r *mutationResolver) AdminBanUser(ctx context.Context, input *BanUserInput) (*AdminBanOutput, error) {
	n, err := strconv.ParseUint(input.UserID, 10, 64)
	if err != nil {
		return &AdminBanOutput{
			Banned: false,
		}, err
	}

	resp, err := r.AdminClient.BanUser(ctx, &adminpb.BanUserRequest{UserId: n})

	if err != nil {
		return &AdminBanOutput{
			Banned: false,
		}, err
	}

	return MapPbBanResponseToBanOutput(resp), nil
}

// AdminUnbanUser is the resolver for the adminUnbanUser field.
func (r *mutationResolver) AdminUnbanUser(ctx context.Context, input *UnbanUserInput) (*AdminUnbanOutput, error) {
	n, err := strconv.ParseUint(input.UserID, 10, 64)
	if err != nil {
		return &AdminUnbanOutput{
			Unbanned: false,
		}, err
	}

	resp, err := r.AdminClient.UnbanUser(ctx, &adminpb.UnbanUserRequest{UserId: n})

	if err != nil {
		return &AdminUnbanOutput{
			Unbanned: false,
		}, err
	}

	return MapPbUnbanResponseToUnbanOutput(resp), nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*UserProfile, error) {
	resp, err := r.Resolver.UserClient.GetProfile(ctx, &emptypb.Empty{})
	if err != nil {
		return nil, err
	}

	return MapUserPbProfileToUserProfile(resp), nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, userID string) (*User, error) {
	n, err := strconv.ParseUint(userID, 10, 64)
	if err != nil {
		return nil, err
	}

	resp, err := r.AdminClient.GetUser(ctx, &adminpb.GetUserRequest{UserId: n})

	if err != nil {
		return nil, err
	}

	return MapPbGetUserResponseToUser(resp), nil
}

// AdminGetProfile is the resolver for the adminGetProfile field.
func (r *queryResolver) AdminGetProfile(ctx context.Context, userID string) (*UserProfile, error) {
	n, err := strconv.ParseUint(userID, 10, 64)
	if err != nil {
		return nil, err
	}

	resp, err := r.AdminClient.GetProfile(ctx, &adminpb.GetProfileRequest{UserId: n})

	if err != nil {
		return nil, err
	}

	return MapAdminPbProfileToUserProfile(resp), nil
}

// AdminGetProfiles is the resolver for the adminGetProfiles field.
func (r *queryResolver) AdminGetProfiles(ctx context.Context, limit int, offset int) (*ProfilesList, error) {
	resp, err := r.AdminClient.GetProfilesList(ctx, &adminpb.GetProfilesListRequest{
		Limit:  uint32(limit),
		Offset: uint32(offset),
	})

	if err != nil {
		return nil, err
	}

	return MapAdminPbProfilesToUserProfiles(resp), nil
}

// ValidateToken is the resolver for the validateToken field.
func (r *queryResolver) ValidateToken(ctx context.Context, accessToken string) (*ValidateTokenOutput, error) {
	return nil, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
